services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
      - backend_sessions:/app/sessions
    environment:
      - PYTHONUNBUFFERED=1
      - CLOUDFLARE_ACCESS_AUD_TAG=${CLOUDFLARE_ACCESS_AUD_TAG}
      - CLOUDFLARE_ACCESS_TEAM_DOMAIN=${CLOUDFLARE_ACCESS_TEAM_DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - DOMAIN=${DOMAIN}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - TIKTOK_CLIENT_KEY=${TIKTOK_CLIENT_KEY}
      - TIKTOK_CLIENT_SECRET=${TIKTOK_CLIENT_SECRET}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend/src:/app/src
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - REACT_APP_DOMAIN=${DOMAIN}
      - REACT_APP_FRONTEND_URL=${FRONTEND_URL}

volumes:
  backend_uploads:
  backend_sessions:
