global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hopper-monitor'
    environment: 'development'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['hopper-dev-otel-collector:8889']
    metrics_path: '/metrics'

  - job_name: 'backend'
    static_configs:
      - targets: ['hopper-dev-backend:8000']
    metrics_path: '/metrics'
