global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hopper-monitor'
    environment: 'production'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['prod-hopper-otel-collector:8889']
    metrics_path: '/metrics'
