apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://prod-hopper-loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      volumeEnabled: true
      discoverServiceName: true
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "fake"
